# Please refer to https://rclone.org/filtering/#filter-from-read-filtering-patterns-from-a-file for configuring rsync filters

# Exclude hidden paths
- .*{/**,}

# Including
+ .config/rclone_script/**
+ Documenti/**
+ Games/**
+ Immagini/**
+ Musica/**
+ Pubblici/**
+ Scrivania/**
+ Video/**

# Exclude everything else
- *
